### ISSUE TITLE
...PropertyProxy::getProperty(): Return value must be of type ...PropertyInterface, null returned in

### ISSUE THREAD

**Issue by uuf6429** [wol-soft/php-json-schema-model-generator#65] opened 2023-01-20 22:36 UTC
![image](https://user-images.githubusercontent.com/230049/213817531-80c06480-07c1-4392-91ac-74d124e585cb.png)

Note that the function return type was defined as non-null and, as you can see in the debugger, the specific key being looked up points to a null.

My suspicion (without digging deep into the code) is that the recursive declaration (line 530 of the schema) might be causing the null?

**Describe the bug**
Attempt to return null on a non-null return during generation.

**Expected behavior**
Generation should have succeeded.

**Schema**
https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json

**Version:**
0.23 (generator) / 0.18 (interfaces)

----

Additionally, the `patternProperties` regex check in `BaseProcessor` line 171 is triggering a failure for pattern `^/(html|css|js)/[^/\n\r]+$`, which to me looks fine, but maybe I'm missing the purpose of the check.

**Comment by wol-soft** [comment] 2023-01-25 09:39
Hi, thanks for the report.

The `patternProperties` issue can be fixed relatively easy (it's an escaping issue). The purpose of the check is to throw an exception on `patternProperties` which provide an invalid pattern to avoid crashes inside the generated code.

The main issue is caused by the combination of recursion and the `oneOf` composition due to the way how compositions are resolved in the library. Each branch of the composition is internally resolved and the result is used to set up correct properties for the compsition (that's the place where the generation process is crashing). Due to the recursion the branch with $ref `name-pattern-template` is not resolved at that point and returns `null` (compare https://github.com/wol-soft/php-json-schema-model-generator/blob/master/src/Model/SchemaDefinition/SchemaDefinition.php#L92).

This will actually not be an easy fix. I've to think about a solution on how to change the resolving.

**Comment by uuf6429** [comment] 2023-01-25 09:55
For the pattern match, you're right, you only need to escape one character, `@preg_match('/' . addcslashes($pattern, '/') . '/', '')`  should work well.

About the recursion, I don't know if this helps, but I solved similar problems in the past by first registering entries and then actually processing them - very similar to what you did in the comment you provided. Unfortunately I don't know enough about this scenario to suggest a more specific approach, sorry.

**Comment by wol-soft** [comment] 2023-01-25 10:21
Exactly, the fix for pattern properties is identical to string properties with a pattern (https://github.com/wol-soft/php-json-schema-model-generator/blob/master/src/PropertyProcessor/Property/StringProcessor.php#L61).

Registering things and resolving them later is also used in this library (eg. the rendering of the code is executed after setting up all internal structures). The mechanic to resolve the issue will be similar. But as mentioned above, I've to think about the exact implementation approach.

**Comment by wol-soft** [comment] 2023-03-13 13:28
Hi @uuf6429,

I've managed to (hopefully 😄) locate all places where the nested recursion causes issues like the original `null`-issue or out of memory errors related to infinite loops etc.

I've set up a branch https://github.com/wol-soft/php-json-schema-model-generator/tree/65-recursive-reference-resolving with the current state. I need to add a lot of tests in this section of recursions (the provided schema seems to be like a final boss for the library). Currently with the branch all existing tests are passing and the provided `web-types` schema is generated.

Do you have any data matching the schema for some manual testing? For the automated tests I'll strip the schema down to the cases causing the issues.

Sorry for the long response delay.

**Closed** 2023-03-30 12:45 UTC
